#include <stdbool.h>
#include <termios.h>

#define ELM327_RESET    		"ATZ"
#define ELM327_ECHO_OFF 		"AT E0"
#define ELM327_LINEFEEDS_OFF	"AT L0"
#define ELM327_EOC      		"\r\n"

#define ELM327_NODATA   "NODATA"
#define ELM327_ERROR    "ERROR"
#define ELM327_OK       "OK"
#define ELM327_NOCONN   "UNABLE TO CONNECT"

#define OBDII_PID_SUPP1                 	0x00
#define OBDII_PID_ENGINE_LOAD               0x04
#define OBDII_PID_ENGINE_COOLANT_TEMP		0x05
#define OBDII_PID_FUEL_PRESSURE				0x0A
#define OBDII_PID_INTAKE_MANIFOLD_PRESSURE	0x0B
#define OBDII_PID_ENGINE_RPM				0x0C
#define OBDII_PID_VEHICLE_SPEED				0x0D
#define OBDII_PID_TIMING_ADVANCE			0x0E
#define OBDII_PID_INTAKE_AIR_TEMP			0x0F
#define OBDII_PID_MAF_AIR_FLOW				0x10
#define OBDII_PID_THROTTLE_POSITION			0x11
#define OBDII_PID_OBD_STANDARD				0x1C
#define OBDII_PID_AUX_INPUT_STATUS			0x1E
#define OBDII_PID_RUN_TIME					0x1F
#define OBDII_PID_SUPP2						0x20
#define OBDII_PID_FUEL_RAIL_PRESSURE		0x22
#define OBDII_PID_FUEL_RAIL_GAUGE_PRESSURE	0x23
#define OBDII_PID_EGR						0x2C
#define OBDII_PID_FUEL_LEVEL				0x2F
#define OBDII_PID_VAPOR_PRESSURE			0x32
#define OBDII_PID_BAROMETRIC_PRESSURE		0x33
#define OBDII_PID_SUPP3						0x40
#define OBDII_PID_CONTROL_MODULE_VOLTAGE	0x42
#define OBDII_PID_ABSOLUTE_LOAD				0x43
#define OBDII_PID_RELATIVE_THROTTLE_POSITION	0x45
#define OBDII_PID_AMBIENT_AIR_TEMPERATURE	0x46
#define OBDII_PID_ETHANOL_FUEL_PERCENT		0x52
#define OBDII_PID_ENGINE_OIL_TEMPERATURE	0x5C
#define OBDII_PID_FUEL_INJECTION_TIMING		0x5D
#define OBDII_PID_ENGINE_FUEL_RATE			0x5E
#define OBDII_PID_SUPP4						0x60
#define OBDII_PID_DEMANDED_PERCENT_TORQUE	0x61
#define OBDII_PID_ACTUAL_PERCENT_TORQUE		0x62
#define OBDII_PID_REFERENCE_TORQUE			0x63

struct elmdev {
	char version[64];
	struct termios tty;
	struct timespec timeout;
	fd_set fdset;
	int fd;
	int baudrate;
	bool is_online;
	
};